//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJewelryTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string StyleNum { get; set; }
        public string StyleName { get; set; }
        public string Desc { get; set; }
        public int JewelryTypeId { get; set; }
        public int CollectionId { get; set; }
        public Nullable<System.DateTime> IntroDate { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> ChainLength { get; set; }
        public Nullable<decimal> RetailRatio { get; set; }
        public Nullable<decimal> RedlineRatio { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Component Component { get; set; }
        public virtual JewelryType JewelryType { get; set; }
    }
}
